# Generated by Django 2.1.7 on 2019-03-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='extended_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=6, null=True)),
                ('teacher', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='student_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.PositiveIntegerField(null=True)),
                ('subject', models.CharField(max_length=64, null=True)),
                ('attendance', models.PositiveIntegerField(default=1, null=True)),
                ('digest', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=64, null=True)),
                ('subject_name', models.CharField(max_length=64, null=True)),
                ('teacher_code', models.PositiveIntegerField(null=True)),
                ('count', models.PositiveIntegerField(null=True)),
                ('lectures', models.PositiveIntegerField(default=1, null=True)),
                ('sha_digest', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
