# Generated by Django 2.1.7 on 2019-03-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='extended_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=6, null=True)),
                ('teacher', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='teacher_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=10, null=True)),
                ('subject_name', models.CharField(max_length=10, null=True)),
                ('teacher_code', models.IntegerField()),
                ('count', models.PositiveIntegerField()),
                ('total_lectures', models.PositiveIntegerField()),
                ('sha_digest', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
