# Generated by Django 2.1.7 on 2019-03-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_user',
            name='class_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_user',
            name='sha_digest',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_user',
            name='subject_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
