# Generated by Django 2.1.7 on 2019-03-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0002_auto_20190324_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_user',
            name='teacher_code',
            field=models.PositiveIntegerField(),
        ),
    ]
