# Generated by Django 2.1.7 on 2019-03-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0004_auto_20190324_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_user',
            name='lectures',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
