# Generated by Django 2.1.7 on 2019-03-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0005_teacher_user_lectures'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.PositiveIntegerField(null=True)),
                ('subject', models.CharField(max_length=64, null=True)),
                ('attendance', models.PositiveIntegerField(null=True)),
                ('digest', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
