# Generated by Django 2.1.7 on 2019-03-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0006_student_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_user',
            name='lectures',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
